version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bus-prospects
    container_name: bus-prospects
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=busprospects
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - mysql
    depends_on:
      - db
  db:
    image: mysql:8.0
volumes:
  db_data:

networks:
  mysql:
    driver: bridge